### ISSUE TITLE
Documentation Improvments

### ISSUE THREAD

**Issue by netanelben** [leovigna/web3-redux#62]
### Broken Links (in content table)

Need a fix for the links to:

- [x] Networks (Add Network)
- [x] Displaying React Components
- [x] Selectors
- [x] Redux State
- [x] Built with
- [x] Diagram/Flow Chart describing the flow of fetching / saving data using this lib.

**Comment by leovigna** [comment]
The `/docs` folder now contains an auto-generated Typedoc documentation.
I will be adding more to the README which will serve as the landing page for the docs.
